spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  instance:
    prefer-ip-address: true
  rabbitmq:
    host: 192.168.43.130
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.43.191
    port: 6379
  jpa:
    show-sql: true
  cloud:
    stream:
      bindings:
        myMessage:
          group: order
          content-type: application/json
#链路追踪
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
#测试配置自动刷新
girl:
  name: nicegirl
  age: 19
env: dev
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
eureka:
  instance:
    prefer-ip-address: true
