spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
eureka:
  instance:
    prefer-ip-address: true
  rabbitmq:
    host: 192.168.43.130
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.43.191
    port: 6379
  jpa:
    show-sql: true
girl: 18
logging:
  level:
    org.springframework.cloud.netflix.feign: debug
